// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormControl from "./FormControl.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useState(function () {
    return {
      name: "",
      birthYear: 1990,
      password: "",
      alive: true
    };
  });
  let setData = match[1];
  let data = match[0];
  let onSubmit = function (ev) {
    ev.preventDefault();
    console.log(data);
  };
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Yozora"
      }),
      JsxRuntime.jsxs("form", {
        children: [
          JsxRuntime.jsx(FormControl.FormControl.make, {
            inputProps: {
              placeholder: "bvb Jimmy Frey",
              required: true
            },
            formValue: {
              TAG: "Text",
              value: data.name,
              onChange: (function (v) {
                setData(function (d) {
                  return {
                    name: v,
                    birthYear: d.birthYear,
                    password: d.password,
                    alive: d.alive
                  };
                });
              })
            },
            id: "name",
            labelText: "Naam"
          }),
          JsxRuntime.jsx(FormControl.FormControl.make, {
            inputProps: {
              placeholder: "birthyear",
              required: true
            },
            formValue: {
              TAG: "Int",
              value: data.birthYear,
              onChange: (function (v) {
                setData(function (d) {
                  return {
                    name: d.name,
                    birthYear: v,
                    password: d.password,
                    alive: d.alive
                  };
                });
              })
            },
            id: "birthYear",
            labelText: "Geboorte jaar"
          }),
          JsxRuntime.jsx(FormControl.FormControl.make, {
            formValue: {
              TAG: "Boolean",
              value: data.alive,
              onChange: (function (v) {
                setData(function (d) {
                  return {
                    name: d.name,
                    birthYear: d.birthYear,
                    password: d.password,
                    alive: v
                  };
                });
              })
            },
            id: "alive",
            labelText: "Are you alive?"
          }),
          JsxRuntime.jsx("button", {
            children: "Submit",
            type: "submit"
          })
        ],
        onSubmit: onSubmit
      }),
      JsxRuntime.jsx("code", {
        children: JsxRuntime.jsx("pre", {
          children: Core__Option.getOr(JSON.stringify(data, undefined, 4), "meh")
        })
      })
    ]
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
